name: vcontrold
description: Homeassistant addon which uses the vcontrold deamon and connect to a Viessmann heating system. To get get the values, the `vclient` tool is used.
version: 0.0.1
slug: vcontrold
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
startup: application
boot: auto
ports:
    3002/udp: 3002
map:
    - config
usb: true
